
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitarot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apitarot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: apitarot
        image: don616/apitarot:{{TAG}}
        ports:
        - containerPort: 8081
  selector:
    matchLabels:
      app: apitarot

---

apiVersion: v1
kind: Service
metadata:
  name: apitarot
spec:
  selector:
    app: apitarot
  ports:
  - port: 80
    targetPort: 8081
  type: LoadBalancer
